project: 
  type: website
  
website: 
  page-navigation: true
  title: "MAR 580 - Fall 2025" 
  site-url: "https://gavinfay.github.io/mar580-advpopmod-f25" 
  repo-url: https://github.com/gavinfay/mar580-advpopmod-f25 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Gavin Fay, 2025, and CC-By Openscapes, 2024"
    
  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://thefaylab.com
        text: "thefaylab.com"
      - icon: github
        href: https://github.com/gavinfay/mar580-advpopmod-f25
        text: "MAR580 website"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: course-syllabus.qmd
        text: Syllabus
      - section: "Projects"
        contents:
          - href: project-description.qmd
            text: Description      
      - section: "Materials"
        contents:
          - href: materials/2025-09-04/index.qmd
            text: "2025-09-04"


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
