---
title: "Syllabus"
---

[**Click here**](syllabus/MAR580-ADVPOPMOD_syllabus_f2025_web_2025-08-28.pdf "PDF of syllabus") **to download a PDF copy of the syllabus. *(****last updated 2025-08-28)*

**Semester: Fall 2025**

**Course Number: MAR 580**

**Course Title: Advanced Population Modeling for Management of Living Natural Resources**

**Instructors:** Gavin Fay, Associate Professor

```         
        School for Marine Science & Technology
```

SMAST East 228; (508) 910-6363; [gfay\@umassd.edu](mailto:gfay@umassd.edu)

**Class Location:** SMAST East Room 247

```         
        836 S Rodney French Blvd, New Bedford, MA 02744

        and synchronous via Zoom
```

**Class Time:** Tuesday/Thursday 2:00-3:30

**Course website:** [gavinfay.github.io/mar580-advpopmod-f25](http://gavinfay.github.io/mar580-advpopmod-f25)

**Student Hours:** Mon 2:00-3:00, Tue 3:30-4:30, Thu 3:30-4:30

\

World events, including COVID-19, continue to create uncertainty. These and other topics (both shared and non visible) will at times create stress within our learning community. I want you to succeed in this course and will do what I can to help support your being able to meet our learning objectives. Please communicate with me if there are additional things I can do to help support you.

**Code of Conduct:** This class follows the[Fay Lab Code of Conduct](https://thefaylab.github.io/lab-manual/03-code-of-conduct.html), which applies to all class spaces, including classrooms, Zoom calls, class GoogleDocs or other materials, and student hours. You can also read my lab’s[lab culture and philosophy](https://thefaylab.github.io/lab-manual/02-lab-culture-philosophy.html), which underpins my approach to teaching and collaboration.

\

**Course Description:** Instruction, demonstration and exercises in advanced statistical methods for estimation of population models for management of living natural resources. Principles of statistical inference and process-based model building recognizing uncertainty will be outlined. A wide range of population assessment methods will be developed through statistical programming and applied to fisheries and marine mammal data sets to fit complex nonlinear models by estimating values for parameters and associated uncertainty. Programming software for implementing these models, including Template Model Builder and STAN will be used for class labs and assignments for both maximum likelihood and Bayesian estimation. The course is designed to train students to “have the ability to conduct high-quality scientific research in stock assessment, fishery population dynamics and related fields” (U.S. Dept. Commerce and U.S. Dept. Education 2008 NOAA Tech. Mem. NMFS-F/SPO-91).

\

**Course Objectives:**

1.  Ability to apply principles underlying process based model building

2.  Familiarity with advanced stock assessment models and their implementation

3.  Experience in model building and parameter estimation

4.  Understanding of quantitative theories, model diagnostics and results

\

**Number of Credits:** 3

\
\

**Prerequisites:**

Students should have taken coursework in applied statistics (e.g. MAR 536) and population dynamics (e.g. MAR 544), or seek permission from the instructors. The Ecological Detective, by Hilborn & Mangel, will serve as a good preparation and perspective on the course topics.

\

Students are advised to contact the instructor ahead of the course to review their preparation – Dr. Fay will provide reading and review preparation material for self-study over the summer.

\

Students should be familiar with the statistical programming software R, at an intermediate competency level. The following free resources are excellent refreshers or introductory training material for R:

-   R for data science: <https://r4ds.had.co.nz/>

-   Software carpentry R lessons: <https://software-carpentry.org/lessons/>

-   Posit (formerly RStudio) [Education resources](https://education.rstudio.com/learn/)

-   Swirlstats (learn R in R): <https://swirlstats.com/>

\

**Required Hardware:** Class will take place in the SMAST-East computer teaching lab. Individual laptop computers will be required to complete in-class and in-lab exercises and coursework. Pair programming approaches are encouraged during class sessions. Please contact the instructor if the computing requirement creates difficulty for your participation in the course; SMAST laptops may be able to be made available for in-class use. The university library also has laptops available for students to borrow.

\

**Required Software:** 

We will make use of several software packages, but the primary ones you will need:

1.  R (free download at <http://r-project.org>). Students should also install Rstudio, an integrated development environment for R, free download at [posit.co/](about:blank)).

2.  Template Model Builder (see <https://github.com/kaskr/adcomp/wiki/Download> for installation instructions, and troubleshooting).

I will walk through installation and use of TMB and reorient people to the RStudio IDE as part of the software during our first lab session. You should update your version of both R and RStudio for the course (I will distribute the version of R that I shall be using for the course later this summer). If needed, web browser access to R sessions will also be provided through a cloud-based instance of RStudio via posit.cloud. Other IDEs are available (e.g. VS Code, Positron), and you may use the platform of your choice, however because I have to choose something to teach in, I will use RStudio in explanations and examples.

\

**Course Materials:** Materials will be distributed through a dedicated course website, and if needed, an RStudio Cloud project. All lectures and labs will be recorded using Zoom.

 

**Remote participation:** To facilitate off-campus attendance and engagement in the course, as well as ensuring the course is available and accessible, class sessions will be broadcast via Zoom in addition to in-person meetings. Zoom information can be found at the top of this syllabus and in course emails. A web link to the recordings will be shared so that these are immediately available.

\

**Textbook**

We will be using the Newman et al. (2014) book as a primary source, though this will be supplemented with chapters from other books and from papers, to be distributed and linked to via the course website. The textbook is available in ebook format through the UMass Dartmouth library system.

\

Newman, K. B., Buckland, S. T., Morgan, B. J., King, R., Borchers, D. L., Cole, D. J., Besbeas, P., Gimenez, O., & Thomas, L. (2014). Modelling Population Dynamics. Model formulation, fitting and assessment using state-space methods. Springer.

[https://umassd.primo.exlibrisgroup.com/permalink/01MA_DM_INST/1q2aha6/alma9914475605501301](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fumassd.primo.exlibrisgroup.com%2Fpermalink%2F01MA_DM_INST%2F1q2aha6%2Falma9914475605501301&data=05%7C02%7Cgfay%40umassd.edu%7C9dbabe15cdce4eb2ac4a08dde1b852a8%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638914903963372486%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=5hlk3h2t5P%2BBA%2FI9TxUiOzYUbZLPuVBa5i%2FJP5r3coU%3D&reserved=0)

\
\

**Course outline and schedule** (subject to change):

\

|  |  |  |  |
|------------------|------------------|------------------|------------------|
| **Date** | **Day** | **Topic** | **Key info** |
| Sep 4 | Th | Numerical methods review, model fitting in R |  |
| Sep 9\* | Tu | process-based model building, matrix pop dy models | HW 1 assigned |
| Sep 11 | Th | state-space models |  |
| Sep 16 | Tu | NO CLASS - ICES ANNUAL SCIENCE CONFERENCE |  |
| Sep 18 | Th | NO CLASS - ICES ANNUAL SCIENCE CONFERENCE |  |
| Sep 23 | Tu | Introduction to Template Model Builder |  |
| Sep 25 | Th | TMB session 02, surplus production models |  |
| Sep 30 | Tu | TMB session 03, coho salmon example | HW1 due |
| Oct 2 | Th | Coho salmon lab review, HW2 (Steller sea lion modeling) assigned | HW 2 assigned |
| Oct 7 | Tu | age-structured models, statistical catch at age |  |
| Oct 9 | Th | model evaluation, simulation testing | HW 2 due |
| Oct 14 | Tu | integrated population modeling I |  |
| Oct 16 | Th | integrated population modeling II | HW 3 assigned |
| Oct 21 | Tu | assessment model continuum and data limited methods |  |
| Oct 23 | Th | assessment model continuum and data limited methods |  |
| Oct 28 | Tu | diagnostics and data-weighting | HW 3 due |
| Oct 30 | Th | reference point estimation |  |
| Nov 4 | Tu | projections, decision tables |  |
| Nov 6 | Th | Bayesian estimation, MCMC |  |
| Nov 11 | Tu | NO CLASS - Veterans Day |  |
| Nov 13 | Th | covariates and time-varying parameters | HW 4 assigned |
| Nov 18 | Tu | Stock assessment software packages |  |
| Nov 20 | Th | Woods Hole Assessment Model |  |
| Nov 25 | Tu | multispecies models | HW 4 due |
| Nov 27 | Th | NO CLASS – THANKSGIVING |  |
| Dec 2 | Tu | multi-state and tag recovery models |  |
| Dec 4 | Th | more capture recapture models |  |
| Dec 9 | Tu | student project presentations | draft reports due |
| Dec 15 | Mo | course review |  |

\

This syllabus is a guide and every attempt is made to provide an accurate overview of the course. However, circumstances and events may make it necessary for the instructor to modify the syllabus during the semester and may depend, in part, on the progress, needs, and experiences of the students. Changes to the syllabus will be made in writing with advance notice.

\
\

**Evaluation procedures:**

1.  Four homework assignments (70%) on advanced population models will be evaluated based on analytical approach, correct solution, and appropriate interpretation. Analytical components of assignments should include submission of complete analytical results (e.g., model scripts and input and output files). Assignments will integrate over course material and expand on the in-class computer exercises. Assignments should be accompanied by a written report (e.g. Rmarkdown or Word document) that provides answers to the assignment questions. Assignments are due before class on the due date. Students can resubmit revised solutions for full credit.

2.  A small research project (20%) that applies one or more of the methods in class to a relevant dataset or problem. We will discuss possible projects at the start of semester, based on student interests. Ideally, projects will involve small teams of students working collaboratively. Grade will be based on two in-class verbal updates (3 minute presentation) during the semester (5% course grade), and a final verbal project presentation (10% course grade) accompanied by a short written project report (5% course grade) due at the end of the semester.

3.  Participation (10%) during class, including engagement in discussions on class readings, and reflection on learning. This includes two self-reflection statements in the middle and at the end of the course asking students to assess their learning. Attendance at the weekly classes and at student hours is the best way to understand topics and assignments.

\

**Class Policies:**

1.  Grades will be reduced for all unexcused late submissions of assignments, with a 10% reduction for each day after the deadline. Requests for extended deadlines will be considered up to one day before the deadline. Unexcused assignments submitted later than three days after the deadline will not be graded. 

2.  Failure to complete any of the requirements for evaluation will result in a score of zero for missing components. At the student's request, and no more than 48 hours after the final due date for the class, an incomplete grade may be given only in exceptional circumstances at the discretion of the instructor. The student must be passing the course at the time of the request or be sufficiently close to passing that the instructor believes that upon completion of the work, the student will pass the course. If the work is not completed within one year of recording the I, the grade will become an F(I).

3.  This 3-credit class involves three hours per week of in-class work and an average of six hours per week of out-of-class work is expected.

4.  University policy on academic dishonesty, including plagiarism, applies (see:  <https://www.umassd.edu/studentaffairs/studenthandbook/academic-regulations-and-procedures/>).

5.  Electronic communications about the course will be conducted via email. I will endeavour to respond to emails about the course within 24 hours of your message, though this will be longer at times and also at weekends (for example, emails sent to me on Friday will likely not be replied to until Monday). Plan accordingly. While I may send emails at times that are convenient for me, I do not expect you to respond outside of your usual working hours. As per University policy, students are responsible for all official correspondence sent to their standard UMD e-mail address (\@umassd.edu).

6.  This course, including student participation, will be recorded on video by the instructor and will be available to students in the course for viewing remotely and after each session. As the Zoom recordings will contain student work, please do not share videos beyond the course attendees without the explicit permission of the instructor. Other course materials will be publicly available online.

7.  If you have read this far, please use google search to find a picture of a flightless bird that best reflects your response to coding error messages, and send it to Gavin Fay attached to an email with the subject line “Here is a response to an error message”, worth an extra 5 points on one homework assignment.

8.  Available academic support services are available at: [www.umassd.edu/nfi/teaching-and-advising/course-syllabus/sample-disability-statement](http://www.umassd.edu/nfi/teaching-and-advising/course-syllabus/sample-disability-statement)  

9.  SMAST Code of Conduct and Diversity statement:<https://www.umassd.edu/media/umassdartmouth/smast/lab-pdf-files/SMAST-Code-of-Conduct-and-Diversity-Statement.pdf>

\

**A full description of Academic Policies associated with this and other UMass Dartmouth courses can be found at:** <https://www.umassd.edu/provost/resourcesforfaculty/syllabus-language/>

\

**Title IX statement:** The purpose of a university is to disseminate information, as well as to explore a universe of ideas, to encourage diverse perspectives and robust expression, and to foster the development of critical and analytical thinking skills. In many classes, including this one, students and faculty examine and analyze challenging and controversial topics.

 

If a topic covered in this class triggers post-traumatic stress or other emotional distress, please discuss the matter with the professor or seek out confidential resources available from the Counseling Center,<http://www.umassd.edu/counselling/>, 508-999-8648 or -8650, or the Victim Advocate in the Center for Women, Gender and Sexuality,<http://www.umassd.edu/sexualviolence/>, 508-910-4584. In an emergency contact the Department of Public Safety at 508-999-9191 24 hrs./day.

 

UMass Dartmouth, following national guidance from the Office of Civil Rights, requires that faculty follow UMass Dartmouth policy as a “mandated reporter” of any disclosure of sexual harassment, abuse, and/or violence shared with the faculty member in person and/or via email. These disclosures include but are not limited to reports of sexual assault, relational abuse, relational/domestic violence, and stalking. While faculty are often able to help students locate appropriate channels of assistance on campus, disclosure by the student to the faculty member requires that the faculty member inform the University’s Title IX Coordinator in the Office of Diversity, Equity and Inclusion at 508-999-8008 to help ensure that the student’s safety and welfare is being addressed, even if the student requests that the disclosure not be shared.

For confidential counseling support and assistance, please go to<http://www.umassd.edu/sexualviolence/>

\

**Technology Expectations**

I expect that everyone will maintain a classroom conducive to learning. Thus, everyone is expected to behave with basic politeness, civility, and respect for others. In particular, talking in class is okay if it’s part of a class discussion, actively troubleshooting code during lab exercises, or with me. Private communications are not permitted. Neither are reading extraneous materials, using electronic equipment off task, or sleeping. Technology is allowed to aid in learning and understanding material. However, please do not use a personal device for any purpose unrelated to our class. All devices should be silenced. Cell phones should be put away when they are not being used for class activities (e.g. taking pictures of work, recording eachother giving practice talks, etc.). If you need to take a call or text during class please step outside. Suggestions for improvement on the class technology policy are welcome at any time. Any concern about the course should be brought first to my attention.

\

**AI, LLMs, and BS** (credit to[Andrew Heiss](https://www.andrewheiss.com/))

AI tools are fast changing the landscape when it comes to work. This is especially true for coding, many software are embedding AI into them to assist users produce work and learn. While there is a relatively large component of the class related to scientific programming, we are doing this to support our statistical learning – the key objectives in the course are learning about and how to apply and evaluate statistical methods, not just the computer code to implement them. I highly recommend not using AI tools such as large language models (LLMs) for generating your writing in this class. I am not opposed to LLMs in many situations. For myself, I am beginning to use[GitHub Copilot](https://github.com/features/copilot) for computer programming-related tasks, most often to assist with tasks I already know how to do, or are similar problems to something I have done before. Like many of you, I have also used ChatGPT to create code that I can then inspect and validate. Chances are if I write this next year my use cases will have increased. What we do know is that using LLMs requires careful skill and attention and practice. I REALLY like [Jenny Bryan’s thoughts on using LLMs to ‘vibe code’](https://www.linkedin.com/posts/libbyheeren_does-jenny-bryan-vibe-code-her-thoughts-activity-7364321666929209344-GhUv?utm_source=share&utm_medium=member_desktop&rcm=ACoAAC8O2nIBuNs2rY_ZgoNxCL8xLTyb-I9b0Lg) (sidenote: Asking yourself “What Would Jenny Bryan Do?” is a pretty good lifehack when it comes to data science in my view). Google Docs and Microsoft Word now have built-in text-generation tools where you can start writing a sentence and let the machine take over the rest. ChatGPT and other services let you generate multi-paragraph essays with plausible-looking text. I encourage you to **please not use these for writing**. There’s a reason most university classes require some sort of writing, like reading reflections, essay questions, and research papers.[The process of writing is actually the process of thinking](https://www.latimes.com/opinion/story/2023-06-20/google-microsoft-chatgpt-ai-writing-assistants-artificial-intelligence):

Writing is hard because the process of getting something onto the page helps us figure out what we think—about a topic, a problem or an idea. If we turn to AI to do the writing, we’re not going to be doing the thinking either. That may not matter if you’re writing an email to set up a meeting, but it will matter if you’re writing a business plan, a policy statement or a court case. ([Rosenzweig 2023](https://www.latimes.com/opinion/story/2023-06-20/google-microsoft-chatgpt-ai-writing-assistants-artificial-intelligence))

Using LLMs and AI to generate this writing will not help you think through the materials. You can create text and meet the suggested word count and finish the assignment, but the text will be meaningless. There’s an official philosophical term for this kind of writing:[bullshit](https://doi.org/10.1007/s10676-024-09775-5) ([Hicks, Humphries, and Slater 2024](https://link.springer.com/article/10.1007/s10676-024-09775-5);[Frankfurt 2005](https://doi.org/10.1515/9781400826537)). Philosophical bullshit is “speech or text produced without concern for its truth” ([Hicks, Humphries, and Slater 2024](https://link.springer.com/article/10.1007/s10676-024-09775-5)). Bullshit isn’t truth, but it’s also not lies (i.e. the opposite of truth). LLMs and AI systems like ChatGPT, Gemini, Claude, and so on are bullshit machines. That might sound hyperbolic, but at a technological level, that’s literally what they do. Do not replace the important work of writing your thoughts, perspectives, and critique with AI bullshit. Remember that the point of writing is to help crystallize your thinking. Chugging out words that make it look like you read and understand the content will not help you learn. In your project report, I want to see good engagement with the analyses that you have performed and your research questions. I want to see your thinking process. I want to see your personal insights about your work and its importance. I don’t want to see a bunch of words that look like a human wrote them. **That’s not useful for future you**. That’s not useful for me. 

I will not spend time trying to guess if your assignments are AI-generated. If you do turn in AI-produced content, I won’t automatically give you a zero. I’ll grade your work based on its own merits. Remember that text generated by these platforms is philosophical bullshit. Since it has nothing to do with truth, it will not—by definition—earn good grades.

\

**Primary & Suggested Reading**

More readings will be added to the course website. A class Zotero library will contain information for all referenced material during the course.

\

Bolker, B. M. 2008. Ecological models and data in R. Princeton University Press. . (draft pdf at <https://ms.mcmaster.ca/~bolker/emdbook/book.pdf> )

Brooks, M.E., Kristensen, K., van Benthem, K.J., Magnusson, A., Berg, C.W., Nielsen, A., Skaug, H.J., Machler, M. and Bolker, B.M., 2017. glmmTMB balances speed and flexibility among packages for zero-inflated generalized linear mixed modeling. The R journal, 9(2), pp.378-400.

Caddy, J.F., 1999. Fisheries management in the twenty-first century: will new paradigms apply?. Reviews in Fish biology and Fisheries, 9(1), pp.1-43.

Cadrin, S.X. 2014 Do Not Believe Your Model Results. In Future of Fisheries: Perspectives for the Next Generation of Professionals, A. Lynch, N. Leonard & W. Taylor, eds. American Fisheries Society Press.

Cooch E & G White, eds. 2014. Program MARK: a gentle introduction. 13th edition.

Cope, J. M. (2024). The good practices of practicable alchemy in the stock assessment continuum: Fundamentals and principles of analytical methods to support science-based fisheries management under data and resource limitations. Fisheries Research, 270, 106859.

Deroba J.J. and 30 co-authors. 2015. Simulation testing the robustness of stock assessment models to error: some results from the ICES Strategic Initiative on Stock Assessment Methods. ICES JMS 72: 19-30.

Dorn M. 2002. Advice on west coast rockfish harvest rates from Bayesian meta-analysis of stock- recruit relationships. North American Journal of Fisheries Management, 22: 280–300.

Haddon, M. 2001. Modelling and Quantitative Methods in Fisheries. CRC Press. Online R version: <https://haddonm.github.io/URMQMF/> 

Hilborn, R. 1990. Estimating the parameters of full age structured models from catch and abundance data. Int. North Pac. Fish. Comm. Bull. 50:207-213.

Hilborn, R. and Mangel, M., 1997. The ecological detective: confronting models with data. Princeton University Press.

Hilborn, R. and C.J. Walters. 1992. Quantitative Fisheries Stock Assessment: Choice, Dynamics, and Uncertainty. Chapman and Hall. 

Hobbs, N.T. and Hooten, M.B., 2015. Bayesian models: a statistical primer for ecologists. Princeton University Press.

Kristensen, K., Nielsen, A., Berg, C.W., Skaug, H. and Bell, B., 2015. TMB: automatic differentiation and Laplace approximation. arXiv preprint arXiv:1509.00660.

Legault, C.M. and V.R. Restrepo. 1998. A flexible forward age-structured assessment program. ICCAT Working Doc. SCRS/98/58.

Mace, P.M. 1994. Relationships between Common Biological Reference Points Used as Thresholds and Targets of Fisheries Management Strategies. Canadian Journal of Fisheries and Aquatic Sciences, 1994, 51: 110-122, <https://doi.org/10.1139/f94-013>.

Maunder MN & AE Punt. 2013. A review of integrated analysis in fisheries stock assessment. Fisheries Research 142: 61-74.

Methot Jr, R. D., & Wetzel, C. R. (2013). Stock synthesis: a biological and statistical framework for fish stock assessment and fishery management. Fisheries Research, 142, 86-99.

Minte-Vera, C. V., Maunder, M. N., Aires-da-Silva, A., Xu, H., Valero, J. L., Teo, S. L., ... & Ducharme-Barth, N. D. (2024). The use of conceptual models to structure stock assessments: A tool for collaboration and for “modelling what to model”. Fisheries Research, 279, 107135.

Nielsen, A., & Berg, C. W. (2014). Estimation of time-varying selectivity in stock assessments using state-space models. Fisheries Research, 158, 96-101.

Nolan and Stoudt. 2021. Communicating with Data. The art of writing for data science. Chapter 4: Communicating through statistical graphs. P71-100.

Punt, A. E. (2023). Those who fail to learn from history are condemned to repeat it: A perspective on current stock assessment good practices and the consequences of not following them. Fisheries Research, 261, 106642.

Punt, A. E., & Hilborn, R. 1997. Fisheries stock assessment and decision analysis: the Bayesian approach. Reviews in Fish Biology and Fisheries, 7(1), 35-63.

Punt, A. E., Dunn, A., Elvarsson, B. Þ., Hampton, J., Hoyle, S. D., Maunder, M. N., ... & Nielsen, A. (2020). Essential features of the next-generation integrated fisheries stock assessment package: a perspective. Fisheries Research, 229, 105617.

Quinn, T.J., 2003. Ruminations on the development and future of population dynamics models in fisheries. Natural Resource Modeling, 16(4), pp.341-392.

Restrepo. V.R. & Legault, C.M. 1998. A Stochastic Implementation of an Age-Structured Production Model. In Fishery Stock Assessment Models Alaska Sea Grant College Program AK-SG-98-01, 1998.

​​Stock, B. C., & Miller, T. J. (2021). The Woods Hole Assessment Model (WHAM): a general state-space assessment framework that incorporates time-and age-varying processes via random effects and links to environmental covariates. Fisheries Research, 240, 105967.

Thorson, J. T., & Minto, C. 2014. Mixed effects: a unifying framework for statistical modelling in fisheries biology. ICES Journal of Marine Science. doi: 10.1093/icesjms/fsu213

Tredennick, A. T., Hooker, G., Ellner, S. P., & Adler, P. B. (2021). A practical guide to selecting models for exploration, inference, and prediction in ecology. Ecology, 102(6), e03336.
